import Dragon64.Finite
set_option maxRecDepth 1000000
set_option maxHeartbeats 0
namespace Dragon64

def multiply (m n : Nat) : Nat :=
  ((a m * a n + b m * c n) % 8) +
  8 * ((a m * b n + b m * d n) % 8) +
  64 * ((c m * a n + d m * c n) % 8) +
  512 * ((c m * b n + d m * d n) % 8)

def wordMatrix : List Bool → Nat
  | [] => identity
  | bit :: rest => multiply (if bit then generatorT else generatorS) (wordMatrix rest)

/-- Explicit positive S/T words, checked by the Lean kernel. -/
def generatorWords : List (List Bool) := [
  [false],
  [false, true],
  [false, true, true],
  [false, true, true, true],
  [false, true, true, true, true],
  [false, true, true, true, true, true],
  [true, false, true, true, false, true, false],
  [true, false, true, false],
  [true, true, true, false, true, true, true, false, true, true, true],
  [true, true, true, true, true, false, true, true, true, true, true, false, false, false],
  [true, true, true, false, true, true, true, false, true],
  [true, true, false, true, true, true, false, true, true, false, false, false],
  [true, true, true, false, true, true, true, true, false, true, false],
  [true, true, true, false, true, true, true, false, true, true],
  [true, true, false, true, true, true, false, true, true, false, true, false, false],
  [true, true, true, false, true, true, true, false],
  [true, true, true, false, true, true, true, false, true, true, true, false, false],
  [true, true, true, false, true, true, true, false, false, false],
  [true, true, false, true, true, true, false, true, true, false, true],
  [true, true, true, false, true, true, true, false, true, true, false, false],
  [true, true, true, false, true, true, true, true, false, true, false, false, false],
  [true, true, false, true, true, true, false, true, true, false],
  [true, true, true, false, true, true, true, false, true, false, false],
  [true, true, true, true, true, false, true, true, true, true, true, false],
  [false, false, false],
  [true, false, true, false, false, false],
  [true, false, true, true, false, true, false, false, false],
  [false, true, true, true, true, true, false, false],
  [false, true, true, true, true, false, false],
  [false, true, true, true, false, false],
  [false, true, true, false, false],
  [false, true, false, false],
  [],
  [false, true, false, false, false],
  [false, true, true, false, false, false],
  [false, true, true, true, false, false, false],
  [false, true, true, true, true, false, false, false],
  [false, true, true, true, true, true, false, false, false],
  [true, false, true, true, false, true],
  [true, false, true],
  [false, true, false, true, false, false, false],
  [false, true, true, false, true, false, false, false],
  [false, true, true, true, false, true, false, false, false],
  [false, true, true, true, true, false, true, false, false, false],
  [false, true, true, true, true, true, false, true, false, false, false],
  [true, false, true, true, false, true, true, false],
  [true, false, true, true, false],
  [true, false],
  [true, true, true, true, true, true],
  [false, true, true, false, true, true, false, true, false, false, false],
  [false, true, true, true, false, true, true, false, true, false, false, false],
  [true, true, false, true, true, true, true, true, false],
  [false, true, true, true, true, true, false, true, true, false, true, false, false, false],
  [true, false, true, true, false, true, true, true, false, true, false],
  [true, false, true, true, true, false, true, false],
  [true, true, false, true, false],
  [true, true, true, true, true],
  [false, true, false, true, true, true, true, true, false, false],
  [true, true, true, true, false, true, true, false, true, false, false],
  [true, true, true, false, true, true, false, true, true, false, false, false],
  [true, true, true, true, false, true, true, true, true, false, true, false, false],
  [true, true, false, true, true, false, true, true, true, false, true, true, false, false],
  [true, false, true, true, true, false, true, true, false, true, false],
  [true, true, false, true, true, false, true, false],
  [true, true, true, true],
  [false, true, false, true, true, true, true, false, false],
  [true, true, true, true, false, true, true, false, false, false],
  [false, true, true, true, false, true, true, true, true, false, false],
  [true, true, true, true, false, true, true, true, true, false, false, false],
  [true, true, false, true, true, false, true, true, true, false, true, false, false],
  [true, true, true, true, true, false, true, true, false, true],
  [true, false, true, true, true, true, true],
  [true, true, true],
  [false, true, false, true, true, true, false, false],
  [false, true, true, false, true, true, true, false, false],
  [false, true, true, true, false, true, true, true, false, false],
  [true, true, false, true, true, true, true, false, true, false, false],
  [true, true, false, true, true, false, true, true, true, false, false, false],
  [true, true, true, true, true, false, true, true, false],
  [true, false, true, true, true, true],
  [true, true],
  [false, true, false, true, true, false, false],
  [false, true, true, false, true, true, false, false],
  [false, true, true, true, false, true, true, false, false],
  [true, true, false, true, true, true, true, false, false, false],
  [false, true, true, true, true, true, false, true, true, false, false],
  [true, false, true, true, false, true, true, true],
  [true, false, true, true, true],
  [true],
  [false, true, false, true, false, false],
  [false, true, true, false, true, false, false],
  [false, true, true, true, false, true, false, false],
  [false, true, true, true, true, false, true, false, false],
  [false, true, true, true, true, true, false, true, false, false],
  [true, false, true, true, false, true, true],
  [true, false, true, true],
  [false, true, false, true, true, false, false, false],
  [false, true, true, true, true, true, false, true, true, false, false, false],
  [false, true, true, false, true, true, false, false, false],
  [true, false, true, true, false, true, true, true, false],
  [false, true, true, true, false, true, true, false, false, false],
  [true, false, true, true, true, false],
  [true, true, false],
  [true, true, false, true, true, true, true],
  [false, true, false, true, true, true, false, true, false, false, false],
  [true, true, true, true, true, true, false, true, true, false, false],
  [true, true, true, true, true, false, true, true, true, false, false, false],
  [false, true, true, false, true, true, true, false, true, false, false, false],
  [true, false, true, true, true, false, true, true, true],
  [true, false, true, true, true, true, false, true, false],
  [true, true, false, true, true, true],
  [true, true, true, false, true, false],
  [false, true, false, true, true, true, false, true, true, false, true, false, false, false],
  [true, true, true, true, true, true, false, true, false, false],
  [true, false, true, true, false, true, true, true, false, true, true],
  [false, true, true, false, true, true, false, true, true, false, false],
  [true, true, true, false, true, true, true, true, true, false, false, false],
  [true, false, true, true, true, false, true, true],
  [true, true, false, true, true],
  [true, true, true, false, true, true, false, true, false],
  [true, true, true, true, true, true, false, false, false],
  [false, true, true, true, true, true, false, true, true, false, true, false, false],
  [true, false, true, true, false, true, true, true, false, true],
  [false, true, true, false, true, true, false, true, false, false],
  [true, false, true, true, true, false, true],
  [false, true, true, true, false, true, true, false, true, false, false],
  [true, true, false, true],
  [true, true, false, true, true, true, true, true],
  [true, true, true, false, true, true, true, false, true, true, true, false, false, false],
  [true, true, true, true, true, false, true, true, true, true, true, false, false],
  [true, true, true, false, true, true, true, false, true, false, false, false],
  [true, true, false, true, true, true, false, true, true, false, false],
  [true, true, true, false, true, true, true, true, false, true],
  [true, true, true, false, true, true, true, false, true, true, false, false, false],
  [true, true, false, true, true, true, false, true, true, false, true, false],
  [true, true, true, false, true, true, true],
  [false, true, true, true, false, true, true, true, false, false, false],
  [true, true, true, true, true, false, true, true, false, false],
  [false, true, false, true, true, true, false, false, false],
  [true, true, false, true, true, true, true, false, true, false, false, false],
  [true, false, true, true, true, true, false],
  [false, true, true, false, true, true, true, false, false, false],
  [true, true, false, true, true, false, true, true, true],
  [true, true, true, false],
  [true, false, true, true, false, true, true, true, false, true, true, false],
  [true, true, true, true, true, true, false, true, false, false, false],
  [true, true, true, false, true, true, false, true, false, false],
  [true, false, true, true, true, false, true, true, false],
  [false, true, true, false, true, true, false, true, true, false, false, false],
  [false, true, false, true, true, true, false, true, true, false, true],
  [true, true, false, true, true, false],
  [true, true, true, false, true, true, true, true, true],
  [true, true, false, true, true, true, false, true, true, true, false, false, false],
  [true, true, true, true, true, false, true, true, true, true, false, false],
  [false, true, false, true, true, true, false, true, true, false, false],
  [true, true, false, true, true, true, false, true, false, false],
  [true, true, true, false, true, true, true, true, false],
  [false, true, true, false, true, true, true, false, true, true, false, false],
  [true, true, true, true, true, true, false, true, true, false, true],
  [true, true, true, false, true, true],
  [false, true, true, true, false, true, true, true, true, false, true, false, false, false],
  [true, true, true, true, true, false, true, false, false],
  [false, true, false, true, true, true, true, false, true, false, false, false],
  [true, true, true, true, false, true, true, true, true, true, false],
  [true, false, true, true, true, true, true, false, true, false],
  [true, true, true, true, false, true, true, true, false],
  [true, true, false, true, true, false, true, true],
  [true, true, true, true, false, true, false],
  [false, true, true, false, true, true, true, false, true, true, false],
  [true, true, true, true, true, true, false, true, true, false, true, false, false, false],
  [true, true, true, false, true, true, false, false, false],
  [true, true, false, true, true, true, false, true, true, true, false, false],
  [true, true, true, true, true, false, true, true, true, true, false],
  [false, true, false, true, true, true, false, true, true, false],
  [true, true, false, true, true, true, false, true, false],
  [true, true, true, false, true, true, true, true],
  [true, false, true, true, true, false, true, true, true, false, false, false],
  [true, true, true, true, true, false, true, true, true, false, false],
  [false, true, false, true, true, true, false, true, false, false],
  [true, true, false, true, true, true, false, false, false],
  [true, false, true, true, true, true, false, true],
  [false, true, true, false, true, true, true, false, true, false, false],
  [true, true, true, true, true, true, false, true, true, false],
  [true, true, true, false, true],
  [true, true, false, true, true, false, true, true, true, false, true, true, false],
  [true, true, true, true, true, false, false, false],
  [true, true, true, false, true, true, false, true, true, false, false],
  [true, false, true, true, true, false, true, true, false, true],
  [false, true, false, true, true, true, true, true, false],
  [true, true, true, true, false, true, true, true, true, false, true, false],
  [true, true, false, true, true, false, true],
  [true, true, true, true, false, true, true, false, true, false],
  [false, true, false, true, true, true, true, false, false, false],
  [false, true, true, true, false, true, true, true, true, false, false, false],
  [true, true, false, true, true, false, true, true, true, false, true, false, false, false],
  [true, false, true, true, true, true, true, false],
  [true, true, true, true, false],
  [true, true, true, true, false, true, true],
  [true, true, true, true, false, true, true, true, true],
  [true, true, true, true, true, false, true, true, false, true, false],
  [true, true, true, true, true, false, true, false, false, false],
  [true, true, true, true, false, true, true, true, true, true, false, false],
  [true, true, true, true, false, true, true, true, false, false],
  [true, true, true, true, false, true, false, false],
  [false, true, true, true, false, true, true, true, true, false, true],
  [false, true, false, true, true, true, true, false, true],
  [true, false, true, true, true, true, true, false, true, false, false],
  [true, true, false, true, true, false, true, true, false],
  [false, true, true, true, false, true, true, true, true, false, true, false, false],
  [true, true, false, true, true, false, true, true, false, false, false],
  [true, false, true, true, true, true, true, false, true],
  [false, true, false, true, true, true, true, false, true, false, false],
  [true, true, true, true, false, true],
  [true, true, true, true, false, true, true, true],
  [true, true, true, true, false, true, true, true, true, true],
  [true, true, true, true, true, false, true, false],
  [true, true, true, true, false, false, false],
  [true, true, true, true, true, false, true, true, false, true, false, false, false],
  [true, true, true, true, false, true, true, true, true, false, false],
  [true, true, true, true, false, true, true, false, false],
  [true, false, true, true, true, true, true, false, false, false],
  [true, true, false, true, true, false, true, true, true, false, true, false],
  [false, true, true, true, false, true, true, true, true, false],
  [false, true, false, true, true, true, true, false],
  [true, true, true, false, true, true, true, false, true, true, true, false],
  [true, true, true, false, true, true, true, false, false],
  [true, true, false, true, true, true, false, true, true, false, true, false, false, false],
  [true, true, true, false, true, true, true, false, true, true, false],
  [true, true, true, false, true, true, true, true, false, true, false, false],
  [true, true, false, true, true, true, false, true, true],
  [true, true, true, false, true, true, true, false, true, false],
  [true, true, true, true, true, false, true, true, true, true, true],
  [true, true, false, true, true, false, true, true, true, false, true, true, false, false, false],
  [true, true, true, true, false, true, true, false, true, false, false, false],
  [true, true, false, true, true, false, true, false, false],
  [true, true, true, true, false, true, true, true, true, false, true, false, false, false],
  [false, true, false, true, true, true, true, true, false, false, false],
  [true, false, true, true, true, false, true, true, false, true, false, false],
  [true, true, true, false, true, true, false, true, true],
  [true, true, true, true, true, false],
  [true, false, true, true, true, false, true, true, true, false],
  [true, true, true, false, true, false, false],
  [true, true, true, true, true, true, false, true, true, false, false, false],
  [false, true, true, false, true, true, true, false, true],
  [true, false, true, true, true, true, false, true, false, false],
  [true, true, false, true, true, true, false],
  [false, true, false, true, true, true, false, true],
  [true, true, true, true, true, false, true, true, true],
  [false, true, true, false, true, true, true, false, true, true, false, false, false],
  [true, true, true, false, true, true, true, true, false, false],
  [true, true, false, true, true, true, false, true, false, false, false],
  [false, true, false, true, true, true, false, true, true, false, false, false],
  [true, true, true, true, true, false, true, true, true, true, false, false, false],
  [true, true, false, true, true, true, false, true, true, true],
  [true, true, true, false, true, true, false],
  [true, true, true, true, true, true, false, true, true, false, true, false],
  [false, true, true, true, false, true, true, true, true, false, true, false],
  [true, true, true, true, false, true, false, false, false],
  [true, true, false, true, true, false, true, true, false, false],
  [true, true, true, true, false, true, true, true, false, false, false],
  [true, false, true, true, true, true, true, false, true, false, false, false],
  [true, true, true, true, false, true, true, true, true, true, false, false, false],
  [false, true, false, true, true, true, true, false, true, false],
  [true, true, true, true, true, false, true],
  [true, true, false, true, true, true, false, true, true, true, false],
  [true, true, true, false, true, true, false, false],
  [true, true, true, true, true, true, false, true, true, false, true, false, false],
  [false, true, true, false, true, true, true, false, true, true],
  [true, true, true, false, true, true, true, true, false, false, false],
  [true, true, false, true, true, true, false, true],
  [false, true, false, true, true, true, false, true, true],
  [true, true, true, true, true, false, true, true, true, true],
  [true, false, true, true, false, true, true, true, false, true, true, false, false, false],
  [true, true, true, false, true, true, true, true, true, false, false],
  [true, true, false, true, true, false, false, false],
  [false, true, false, true, true, true, false, true, true, false, true, false, false],
  [false, true, true, false, true, true, false, true, true, false],
  [true, false, true, true, true, false, true, true, false, false, false],
  [true, true, true, false, true, true, false, true],
  [true, true, true, true, true, true, false, true, false],
  [false, true, true, true, false, true, true, true, false],
  [true, true, true, false, false, false],
  [true, true, false, true, true, false, true, true, true, false, false],
  [false, true, true, false, true, true, true, false],
  [true, false, true, true, true, true, false, false, false],
  [true, true, false, true, true, true, true, false, true, false],
  [false, true, false, true, true, true, false],
  [true, true, true, true, true, false, true, true],
  [true, true, false, true, true, true, true, true, false, false],
  [true, true, false, true, false, false],
  [false, true, true, true, false, true, true, false, true],
  [true, false, true, true, true, false, true, false, false],
  [false, true, true, false, true, true, false, true],
  [true, false, true, true, false, true, true, true, false, true, false, false],
  [true, true, true, true, true, true, false],
  [false, true, true, true, true, true, false, true, true, false, true],
  [true, true, true, false, true, true, false, true, false, false, false],
  [true, true, false, true, true, false, false],
  [true, false, true, true, true, false, true, true, false, false],
  [true, true, true, false, true, true, true, true, true, false],
  [true, false, true, true, false, true, true, true, false, true, true, false, false],
  [false, true, true, false, true, true, false, true, true],
  [true, true, true, true, true, true, false, true],
  [false, true, false, true, true, true, false, true, true, false, true, false],
  [true, true, true, false, true, false, false, false],
  [true, true, false, true, true, true, false, false],
  [true, false, true, true, true, false, true, true, true, false, false],
  [true, false, true, true, true, true, false, true, false, false, false],
  [false, true, true, false, true, true, true, false, true, false],
  [true, true, true, true, true, false, true, true, true, false],
  [true, true, true, true, true, true, false, true, true],
  [false, true, false, true, true, true, false, true, false],
  [true, true, false, false, false],
  [true, true, false, true, true, true, true, false, false],
  [true, false, true, true, true, false, false, false],
  [false, true, true, true, false, true, true, false],
  [true, false, true, true, false, true, true, true, false, false, false],
  [false, true, true, false, true, true, false],
  [false, true, true, true, true, true, false, true, true, false],
  [false, true, false, true, true, false],
  [false, false],
  [true, false, true, false, false],
  [true, false, true, true, false, true, false, false],
  [false, true, true, true, true, true, false],
  [false, true, true, true, true, false],
  [false, true, true, true, false],
  [false, true, true, false],
  [false, true, false],
  [true, false, false],
  [true, false, true, true, false, false],
  [true, false, true, true, false, true, true, false, false],
  [false, true, true, true, true, true, false, true],
  [false, true, true, true, true, false, true],
  [false, true, true, true, false, true],
  [false, true, true, false, true],
  [false, true, false, true],
  [true, true, false, false],
  [true, false, true, true, true, false, false],
  [true, false, true, true, false, true, true, true, false, false],
  [false, true, true, true, true, true, false, true, true],
  [true, true, false, true, true, true, true, false],
  [false, true, true, true, false, true, true],
  [false, true, true, false, true, true],
  [false, true, false, true, true],
  [true, true, true, false, false],
  [true, false, true, true, true, true, false, false],
  [true, true, true, true, true, false, true, true, false, false, false],
  [true, true, false, true, true, false, true, true, true, false],
  [true, true, false, true, true, true, true, false, true],
  [false, true, true, true, false, true, true, true],
  [false, true, true, false, true, true, true],
  [false, true, false, true, true, true],
  [true, true, true, true, false, false],
  [true, false, true, true, true, true, true, false, false],
  [true, true, true, true, true, false, true, true, false, true, false, false],
  [true, true, false, true, true, false, true, true, true, false, true],
  [true, true, true, true, false, true, true, true, true, false],
  [false, true, true, true, false, true, true, true, true],
  [true, true, true, true, false, true, true, false],
  [false, true, false, true, true, true, true],
  [true, true, true, true, true, false, false],
  [true, true, false, true, true, false, true, false, false, false],
  [true, false, true, true, true, false, true, true, false, true, false, false, false],
  [true, true, false, true, true, false, true, true, true, false, true, true],
  [true, true, true, true, false, true, true, true, true, false, true],
  [true, true, true, false, true, true, false, true, true, false],
  [true, true, true, true, false, true, true, false, true],
  [false, true, false, true, true, true, true, true],
  [true, true, true, true, true, true, false, false],
  [true, true, false, true, false, false, false],
  [true, false, true, true, true, false, true, false, false, false],
  [true, false, true, true, false, true, true, true, false, true, false, false, false],
  [false, true, true, true, true, true, false, true, true, false, true, false],
  [true, true, false, true, true, true, true, true, false, false, false],
  [false, true, true, true, false, true, true, false, true, false],
  [false, true, true, false, true, true, false, true, false],
  [false, true, false, true, false],
  [true, false, false, false],
  [true, false, true, true, false, false, false],
  [true, false, true, true, false, true, true, false, false, false],
  [false, true, true, true, true, true, false, true, false],
  [false, true, true, true, true, false, true, false],
  [false, true, true, true, false, true, false],
  [false, true, true, false, true, false]
]

theorem generator_words_complete : generatorWords.map wordMatrix = sl2 := by decide

theorem every_enumerated_matrix_generated (m : Nat) (h : m ∈ sl2) :
    ∃ w : List Bool, wordMatrix w = m := by
  rw [← generator_words_complete] at h
  obtain ⟨w, _, hw⟩ := List.mem_map.mp h
  exact ⟨w, hw⟩

/-- Generator composition laws on the complete determinant-one enumeration. -/
def generatorActionCheck (g : Nat) : Bool :=
  sl2.all (fun m => (List.range 64).all (fun v =>
    act (multiply g m) v == act g (act m v)))
theorem s_composition_checked : generatorActionCheck generatorS = true := by decide
theorem t_composition_checked : generatorActionCheck generatorT = true := by decide

def pairAct (m p : Nat) := 64 * act m (p / 64) + act m (p % 64)
def pairOrbit (p : Nat) := (sl2.map (fun m => pairAct m p)).eraseDups
def pairRepresentatives : List Nat := [0, 1, 2, 4, 64, 65, 66, 67, 68, 69, 70, 71, 72, 80, 81, 88, 96, 97, 98, 99, 104, 112, 113, 120, 128, 129, 130, 131, 132, 134, 136, 144, 145, 152, 160, 162, 176, 256, 257, 258, 260, 264, 272, 288]
def pairPartition := pairRepresentatives.map pairOrbit

theorem pair_representatives_count : pairRepresentatives.length = 44 := by decide
/-- Sorted equality establishes coverage and multiplicity one simultaneously. -/
theorem pair_partition_exact :
    pairPartition.flatten.mergeSort (fun x y => x ≤ y) = List.range 4096 := by decide


def generatorClosureCheck (g : Nat) : Bool :=
  sl2.all (fun m => sl2.contains (multiply g m))
theorem s_closure_checked : generatorClosureCheck generatorS = true := by decide
theorem t_closure_checked : generatorClosureCheck generatorT = true := by decide

theorem s_preserves_enumeration (m : Nat) (h : m ∈ sl2) :
    multiply generatorS m ∈ sl2 := by
  have hc := (List.all_eq_true.mp s_closure_checked) m h
  simpa using hc

theorem t_preserves_enumeration (m : Nat) (h : m ∈ sl2) :
    multiply generatorT m ∈ sl2 := by
  have hc := (List.all_eq_true.mp t_closure_checked) m h
  simpa using hc

theorem word_in_enumeration (w : List Bool) : wordMatrix w ∈ sl2 := by
  induction w with
  | nil => decide
  | cons bit rest ih =>
    cases bit with
    | false => exact s_preserves_enumeration _ ih
    | true => exact t_preserves_enumeration _ ih

theorem generated_iff_enumerated (m : Nat) :
    (∃ w : List Bool, wordMatrix w = m) ↔ m ∈ sl2 := by
  constructor
  · rintro ⟨w, rfl⟩
    exact word_in_enumeration w
  · exact every_enumerated_matrix_generated m

/-- Each partition block is stable under both generating permutations. -/
def partitionStable (g : Nat) : Bool :=
  pairPartition.all (fun block => block.all (fun p => block.contains (pairAct g p)))
theorem pair_partition_s_stable : partitionStable generatorS = true := by decide
theorem pair_partition_t_stable : partitionStable generatorT = true := by decide

end Dragon64
