import WNSKernel

#print axioms WNSKernel.delegation_budget_no_growth
#print axioms WNSKernel.delegation_depth_decreases
#print axioms WNSKernel.delegation_window_contained
#print axioms WNSKernel.delegation_action_contained
#print axioms WNSKernel.lineage_has_trusted_origin
#print axioms WNSKernel.replay_preserves_history
#print axioms WNSKernel.replay_preserves_grants
#print axioms WNSKernel.revoked_membership_absent
#print axioms WNSKernel.revoked_store_denied
#print axioms WNSKernel.revocation_survives_execution
#print axioms WNSKernel.changed_dependency_stale
#print axioms WNSKernel.unrelated_source_preserves
#print axioms WNSKernel.changed_knowledge_blocks_transition
#print axioms WNSKernel.consistent_chain_reconstructs
#print axioms WNSKernel.mismatched_before_denied
#print axioms WNSKernel.inconsistent_receipt_denied
#print axioms WNSKernel.step_receipt_consistent
#print axioms WNSKernel.step_receipt_replays
#print axioms WNSKernel.FalseGreen.equal_commitments_distinct_states
#print axioms WNSKernel.FalseGreen.authenticated_does_not_establish_truth
#print axioms WNSKernel.FalseGreen.zero_exit_can_execute_no_checks
#print axioms WNSKernel.FalseGreen.eligibility_without_authority
#print axioms WNSKernel.rejection_preserves
#print axioms WNSKernel.rejected_verdict_preserves
#print axioms WNSKernel.accepted_requires_eligibility
#print axioms WNSKernel.grants_preserved
#print axioms WNSKernel.receipt_binds_before
#print axioms WNSKernel.receipt_binds_after
#print axioms WNSKernel.receipt_binds_action
#print axioms WNSKernel.receipt_recorded
#print axioms WNSKernel.history_preserved
#print axioms WNSKernel.stale_denied
#print axioms WNSKernel.empty_grants_denied
#print axioms WNSKernel.revoked_denied
#print axioms WNSKernel.expired_denied
#print axioms WNSKernel.delegated_scope_no_growth
#print axioms WNSKernel.seam_has_no_authority
#print axioms WNSKernel.seam_denied
#print axioms WNSKernel.replay_cons
#print axioms WNSKernel.replay_append
#print axioms WNSKernel.weaver_accepts
#print axioms WNSKernel.weaver_rejects_self_proposal
#print axioms WNSKernel.commons_route_without_authority
#print axioms WNSKernel.copied_state_requires_regrant
#print axioms WNSKernel.evidence_without_grant_denied
