import WNSKernel

#print axioms WNSKernel.delegation_budget_no_growth
#print axioms WNSKernel.delegation_depth_decreases
#print axioms WNSKernel.delegation_window_contained
#print axioms WNSKernel.delegation_action_contained
#print axioms WNSKernel.lineage_has_trusted_origin
#print axioms WNSKernel.replay_preserves_history
#print axioms WNSKernel.replay_preserves_grants
#print axioms WNSKernel.revoked_membership_absent
#print axioms WNSKernel.revoked_store_denied
#print axioms WNSKernel.revocation_survives_execution
#print axioms WNSKernel.changed_dependency_stale
#print axioms WNSKernel.unrelated_source_preserves
#print axioms WNSKernel.changed_knowledge_blocks_transition
#print axioms WNSKernel.consistent_chain_reconstructs
#print axioms WNSKernel.mismatched_before_denied
#print axioms WNSKernel.inconsistent_receipt_denied
#print axioms WNSKernel.step_receipt_consistent
#print axioms WNSKernel.step_receipt_replays
#print axioms WNSKernel.FalseGreen.equal_commitments_distinct_states
#print axioms WNSKernel.FalseGreen.authenticated_does_not_establish_truth
#print axioms WNSKernel.FalseGreen.zero_exit_can_execute_no_checks
#print axioms WNSKernel.FalseGreen.eligibility_without_authority
#print axioms WNSKernel.rejection_preserves
#print axioms WNSKernel.rejected_verdict_preserves
#print axioms WNSKernel.accepted_requires_eligibility
#print axioms WNSKernel.grants_preserved
#print axioms WNSKernel.receipt_binds_before
#print axioms WNSKernel.receipt_binds_after
#print axioms WNSKernel.receipt_binds_action
#print axioms WNSKernel.receipt_recorded
#print axioms WNSKernel.history_preserved
#print axioms WNSKernel.stale_denied
#print axioms WNSKernel.empty_grants_denied
#print axioms WNSKernel.revoked_denied
#print axioms WNSKernel.expired_denied
#print axioms WNSKernel.delegated_scope_no_growth
#print axioms WNSKernel.seam_has_no_authority
#print axioms WNSKernel.seam_denied
#print axioms WNSKernel.replay_cons
#print axioms WNSKernel.replay_append
#print axioms WNSKernel.weaver_accepts
#print axioms WNSKernel.weaver_rejects_self_proposal
#print axioms WNSKernel.commons_route_without_authority
#print axioms WNSKernel.copied_state_requires_regrant
#print axioms WNSKernel.evidence_without_grant_denied

#print axioms WNSKernel.Portfolio.changed_dependency_not_current
#print axioms WNSKernel.Portfolio.matching_dependencies_current
#print axioms WNSKernel.Portfolio.unresolved_failure_denies
#print axioms WNSKernel.Portfolio.recorded_failure_denies
#print axioms WNSKernel.Portfolio.correction_preserves_history
#print axioms WNSKernel.Portfolio.recording_preserves_history
#print axioms WNSKernel.Portfolio.recorded_failure_survives_correction
#print axioms WNSKernel.Portfolio.empty_chain_denies
#print axioms WNSKernel.Portfolio.revoked_node_not_live
#print axioms WNSKernel.Portfolio.absent_node_not_live
#print axioms WNSKernel.Portfolio.expired_node_not_live
#print axioms WNSKernel.Portfolio.invalid_parent_chain_denies
#print axioms WNSKernel.Portfolio.both_true
#print axioms WNSKernel.Portfolio.live_head_required
#print axioms WNSKernel.Portfolio.chain_has_trusted_root
#print axioms WNSKernel.Portfolio.preconditions_false_denies
#print axioms WNSKernel.Portfolio.stale_dependency_preserves
#print axioms WNSKernel.Portfolio.failed_insight_preserves
#print axioms WNSKernel.Portfolio.invalid_chain_preserves
#print axioms WNSKernel.Portfolio.every_chain_node_live
#print axioms WNSKernel.Portfolio.revoked_ancestor_denies
#print axioms WNSKernel.Portfolio.delegated_acceptance_example
#print axioms WNSKernel.Portfolio.failure_rejection_example
#print axioms WNSKernel.Portfolio.accepted_requires_live_chain
#print axioms WNSKernel.Portfolio.accepted_requires_insight
#print axioms WNSKernel.Portfolio.accepted_requires_current_dependencies
#print axioms WNSKernel.Portfolio.accepted_has_trusted_origin

#print axioms WNSKernel.Durable.ineligible_preserves
#print axioms WNSKernel.Durable.substitution_denies
#print axioms WNSKernel.Durable.spent_denies
#print axioms WNSKernel.Durable.accepted_request_bound
#print axioms WNSKernel.Durable.eligible_consumes_approval
#print axioms WNSKernel.Durable.spent_preserved
#print axioms WNSKernel.Durable.retry_no_second_effect
#print axioms WNSKernel.Durable.effect_receipt_consistency
#print axioms WNSKernel.Durable.approvals_preserved
#print axioms WNSKernel.Durable.recovery_atomic_cases
#print axioms WNSKernel.Durable.postcommit_retry_preserves
#print axioms WNSKernel.Durable.run_preserves_spent
#print axioms WNSKernel.Durable.historical_replay_denies
#print axioms WNSKernel.Durable.positive_commit_example
#print axioms WNSKernel.Durable.changed_parameters_example

#print axioms WNSKernel.Drift.transitive_changed_source_denies
#print axioms WNSKernel.Drift.two_edge_drift
#print axioms WNSKernel.Drift.closed_stale_set_propagates
#print axioms WNSKernel.Drift.expansion_preserves_stale
#print axioms WNSKernel.Drift.propagation_preserves_stale
#print axioms WNSKernel.Drift.two_hop_executable_example
#print axioms WNSKernel.Drift.insufficient_fuel_counterexample
